application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: protocol-${api.blockchain}-erc20-indexer-api
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  ethereum:
    converter:
      enabled: true
  core:
    filter:
      cors:
        enabled: true
    contract:
      enabled: true

springdoc:
  swagger-ui:
    path: /v0.1/swagger/swagger-ui.html
  api-docs:
    path: /v0.1/swagger/v3/api-docs
