application:
  environment: infura-test

rarible:
  core:
    apm:
      agent:
        enabled: false
  ethereum:
    httpUrl: ${ETH_NODE_HTTP_URL}
    maxFrameSize: 10485760
    websocketUrl: ${ETH_NODE_WS_URL}

spring:
  cloud:
    bootstrap:
      enabled: false
    consul:
      enabled: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

logging:
  logstash:
    tcp-socket:
      enabled: false
      destinations: []



