global:
  network: mainnet

ethereum-erc20-api:
  replicas: 3
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256

polygon-erc20-api:
  replicas: 3
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256

ethereum-erc20-listener:
  resources:
    jvm:
      xmx_megabytes: 2048

polygon-erc20-listener:
  resources:
    jvm:
      xmx_megabytes: 2048

ethereum-gateway:
  service:
    enabled: true
    nodePort: 30116
  resources:
    jvm:
      xmx_megabytes: 1024
  networks:
    additional:
    - 'proxy'

polygon-gateway:
  service:
    enabled: true
    nodePort: 30117
  resources:
    jvm:
      xmx_megabytes: 1024
  networks:
    additional:
    - 'proxy'

ethereum-order-api:
  replicas: 3
  resources:
    jvm:
      xmx_megabytes: 2048
      max_direct_memory_megabytes: 256

polygon-order-api:
  replicas: 3
  resources:
    jvm:
      xmx_megabytes: 2048
      max_direct_memory_megabytes: 256

ethereum-order-listener:
  resources:
    jvm:
      xmx_megabytes: 2048

polygon-order-listener:
  resources:
    jvm:
      xmx_megabytes: 2048

ethereum-nft-api:
  replicas: 3
  resources:
    jvm:
      xmx_megabytes: 1536
      max_direct_memory_megabytes: 256

polygon-nft-api:
  replicas: 3
  resources:
    jvm:
      xmx_megabytes: 1536
      max_direct_memory_megabytes: 256

ethereum-nft-listener:
  resources:
    jvm:
      xmx_megabytes: 2048

polygon-nft-listener:
  resources:
    jvm:
      xmx_megabytes: 2048
      max_direct_memory_megabytes: 1024
