rarible:
  core:
    apm:
      agent:
        enabled: false
  ethereum:
    httpUrl: ${ETH_NODE_HTTP_URL}
    maxFrameSize: 10485760
    websocketUrl: ${ETH_NODE_WS_URL}
  loader:
    broker-replica-set: ${KAFKA_HOSTS}
    loadTasksBatchSize: 50
    workers: 32

spring:
  cloud:
    bootstrap:
      enabled: false
    consul:
      enabled: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

ethereumBlockProcessingDelay: 5000
ethereumMaxProcessTime: 1200000
useNewMongoIndex: true

application:
  environment: infura-test

logging:
  logstash:
    tcp-socket:
      enabled: false
      destinations: []

blockchain:
  scanner:
    kafka:
      broker-replica-set: ${KAFKA_HOSTS}

common:
  kafka-replica-set: ${KAFKA_HOSTS}

api:
  chain-id: 420
  operator:
    private-key: ${NFT_API_OPERATOR_PRIVATE_KEY}
