global:
  network: rinkeby

polygon-nft-listener:
  livenessProbe:
    initialDelaySeconds: 360s
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 128

polygon-gateway:
  service:
    nodePort: 30417