version: '3.9'

services:

  protocol-ethereum-nft-api:
    build:
      context: ../nft/api
      dockerfile: ../../docker/Dockerfile
    image: protocol-ethereum-nft-api
    environment:
      - JAVA_OPTIONS=-Xmx$PROTOCOL_NFT_API_HEAP -Xms$PROTOCOL_NFT_API_HEAP -XX:MaxDirectMemorySize=$PROTOCOL_NFT_API_DIRECT_MEMORY
      - APPLICATION_ENVIRONMENT=$APPLICATION_ENVIRONMENT
      - SPRING_PROFILES_ACTIVE=$APPLICATION_ENVIRONMENT
      - LOGGING_LOGSTASH_TCP-SOCKET_ENABLED=$LOGGING_LOGSTASH_TCP_SOCKET_ENABLED
      - SPRING_CLOUD_CONSUL_CONFIG_ENABLED=$SPRING_CLOUD_CONSUL_CONFIG_ENABLED
      - SPRING_CLOUD_BOOTSTRAP_ENABLED=$SPRING_CLOUD_BOOTSTRAP_ENABLED
      - SPRING_CLOUD_SERVICEREGISTRY_AUTOREGISTRATION_ENABLED=$SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED
      - SPRING_CLOUD_DISCOVERY_ENABLED=$SPRING_CLOUD_DISCOVERY_ENABLED
      - SPRING_DATA_MONGODB_URI=$MONGO_CONNECTION_STRING
      - SPRING_DATA_MONGODB_DATABASE=$NFT_COMMON_DATABASE
      - RARIBLE_ETHEREUM_HTTPURL=$RARIBLE_ETHEREUM_HTTP-URL
      - RARIBLE_ETHEREUM_WEBSOCKETURL=$RARIBLE_ETHEREUM_WEBSOCKET-URL
      - RARIBLE_LOADER_BROKER-REPLICA-SET=$KAFKA_CONNECTION_STRING
      - RARIBLE_CORE_APM_AGENT_ENABLED=$RARIBLE_CORE_APM_AGENT_ENABLED
      - RARIBLE_CORE_APM_WEB_ENABLED=$RARIBLE_CORE_APM_WEB_ENABLED
      - RARIBLE_CORE_APM_ANNOTATION_ENABLED=$RARIBLE_CORE_APM_ANNOTATION_ENABLED
      - REDISURI=$REDIS_URI
      - COMMON_BASE_PUBLIC_API_URL=$NFT_COMMON_BASE_PUBLIC_API_URL
      - COMMON_OPENSEA_LAZY_MINT_ADDRESS=$NFT_COMMON_OPENSEA_LAZY_MINT_ADDRESS
      - COMMON_FACTORY_ERC-721-RARIBLE=$NFT_COMMON_FACTORY_ERC_721_RARIBLE
      - COMMON_FACTORY_ERC-721-RARIBLE-USER=$NFT_COMMON_FACTORY_ERC_721_RARIBLE_USER
      - COMMON_FACTORY_ERC-1155-RARIBLE=$NFT_COMMON_FACTORY_ERC_1155_RARIBLE
      - COMMON_FACTORY_ERC-1155-RARIBLE-USER=$NFT_COMMON_FACTORY_ERC_1155_RARIBLE_USER
      - COMMON_ROYALTY_REGISTRY_ADDRESS=$NFT_COMMON_ROYALTY_REGISTRY_ADDRESS
      - COMMON_KAFKA_REPLICA_SET=$KAFKA_CONNECTION_STRING
      - COMMON_BLOCKCHAIN=$NFT_COMMON_BLOCKCHAIN
      - API_CHAIN_ID=$API_CHAIN_ID
      - API_OPERATOR_PRIVATE_KEY=$API_OPERATOR_PRIVATE_KEY
      - BLOCKCHAIN_SCANNER_KAFKA_BROKER-REPLICA-SET=$KAFKA_CONNECTION_STRING
    ports:
      - "${NFT_COMMON_EXPOSE_PORT}:8080"

  protocol-ethereum-nft-listener:
    build:
      context: ../nft/listener
      dockerfile: ../../docker/Dockerfile
    image: protocol-ethereum-nft-listener
    environment:
      - JAVA_OPTIONS=-Xmx$PROTOCOL_NFT_LISTENER_HEAP -Xms$PROTOCOL_NFT_LISTENER_HEAP -XX:MaxDirectMemorySize=$PROTOCOL_NFT_LISTENER_DIRECT_MEMORY
      - APPLICATION_ENVIRONMENT=$APPLICATION_ENVIRONMENT
      - SPRING_PROFILES_ACTIVE=$APPLICATION_ENVIRONMENT
      - LOGGING_LOGSTASH_TCP-SOCKET_ENABLED=$LOGGING_LOGSTASH_TCP_SOCKET_ENABLED
      - SPRING_CLOUD_CONSUL_CONFIG_ENABLED=$SPRING_CLOUD_CONSUL_CONFIG_ENABLED
      - SPRING_CLOUD_BOOTSTRAP_ENABLED=$SPRING_CLOUD_BOOTSTRAP_ENABLED
      - SPRING_CLOUD_SERVICEREGISTRY_AUTOREGISTRATION_ENABLED=$SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED
      - SPRING_CLOUD_DISCOVERY_ENABLED=$SPRING_CLOUD_DISCOVERY_ENABLED
      - SPRING_DATA_MONGODB_URI=$MONGO_CONNECTION_STRING
      - SPRING_DATA_MONGODB_DATABASE=$NFT_COMMON_DATABASE
      - RARIBLE_ETHEREUM_HTTPURL=$RARIBLE_ETHEREUM_HTTP_URL
      - RARIBLE_ETHEREUM_WEBSOCKETURL=$RARIBLE_ETHEREUM_WEBSOCKET_URL
      - RARIBLE_LOADER_BROKER-REPLICA-SET=$KAFKA_CONNECTION_STRING
      - RARIBLE_CORE_APM_AGENT_ENABLED=$RARIBLE_CORE_APM_AGENT_ENABLED
      - RARIBLE_CORE_APM_WEB_ENABLED=$RARIBLE_CORE_APM_WEB_ENABLED
      - RARIBLE_CORE_APM_ANNOTATION_ENABLED=$RARIBLE_CORE_APM_ANNOTATION_ENABLED
      - REDISURI=$REDIS_URI
      - COMMON_BASE_PUBLIC_API_URL=$NFT_COMMON_BASE_PUBLIC_API_URL
      - COMMON_OPENSEA_LAZY_MINT_ADDRESS=$NFT_COMMON_OPENSEA_LAZY_MINT_ADDRESS
      - COMMON_FACTORY_ERC-721-RARIBLE=$NFT_COMMON_FACTORY_ERC_721_RARIBLE
      - COMMON_FACTORY_ERC-721-RARIBLE-USER=$NFT_COMMON_FACTORY_ERC_721_RARIBLE_USER
      - COMMON_FACTORY_ERC-1155-RARIBLE=$NFT_COMMON_FACTORY_ERC_1155_RARIBLE
      - COMMON_FACTORY_ERC-1155-RARIBLE-USER=$NFT_COMMON_FACTORY_ERC_1155_RARIBLE_USER
      - COMMON_ROYALTY_REGISTRY_ADDRESS=$NFT_COMMON_ROYALTY_REGISTRY_ADDRESS
      - COMMON_KAFKA_REPLICA_SET=$KAFKA_CONNECTION_STRING
      - COMMON_BLOCKCHAIN=$NFT_COMMON_BLOCKCHAIN
      - COMMON_FEATURE-FLAGS_SCANNER-VERSION=$NFT_COMMON_FEATURE_FLAGS_SCANNER_VERSION
      - BLOCKCHAIN_SCANNER_KAFKA_BROKER-REPLICA-SET=$KAFKA_CONNECTION_STRING

  protocol-ethereum-nft-migration:
    build:
      context: ../nft/migration
      dockerfile: ../../docker/Dockerfile
    image: protocol-ethereum-nft-migration
    environment:
      - JAVA_OPTIONS=-Xmx$PROTOCOL_NFT_MIGRATION_HEAP -Xms$PROTOCOL_NFT_MIGRATION_HEAP -XX:MaxDirectMemorySize=$PROTOCOL_NFT_MIGRATION_DIRECT_MEMORY
      - APPLICATION_ENVIRONMENT=$APPLICATION_ENVIRONMENT
      - SPRING_PROFILES_ACTIVE=$APPLICATION_ENVIRONMENT
      - LOGGING_LOGSTASH_TCP-SOCKET_ENABLED=$LOGGING_LOGSTASH_TCP_SOCKET_ENABLED
      - SPRING_CLOUD_CONSUL_CONFIG_ENABLED=$SPRING_CLOUD_CONSUL_CONFIG_ENABLED
      - SPRING_CLOUD_BOOTSTRAP_ENABLED=$SPRING_CLOUD_BOOTSTRAP_ENABLED
      - SPRING_CLOUD_SERVICEREGISTRY_AUTOREGISTRATION_ENABLED=$SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED
      - SPRING_CLOUD_DISCOVERY_ENABLED=$SPRING_CLOUD_DISCOVERY_ENABLED
      - SPRING_DATA_MONGODB_URI=$MONGO_CONNECTION_STRING
      - SPRING_DATA_MONGODB_DATABASE=$NFT_COMMON_DATABASE
      - RARIBLE_ETHEREUM_HTTPURL=$RARIBLE_ETHEREUM_HTTP_URL
      - RARIBLE_ETHEREUM_WEBSOCKETURL=$RARIBLE_ETHEREUM_WEBSOCKET_URL
      - RARIBLE_LOADER_BROKER-REPLICA-SET=$KAFKA_CONNECTION_STRING
      - RARIBLE_CORE_APM_AGENT_ENABLED=$RARIBLE_CORE_APM_AGENT_ENABLED
      - RARIBLE_CORE_APM_WEB_ENABLED=$RARIBLE_CORE_APM_WEB_ENABLED
      - RARIBLE_CORE_APM_ANNOTATION_ENABLED=$RARIBLE_CORE_APM_ANNOTATION_ENABLED
      - REDISURI=$REDIS_URI
      - COMMON_BASE_PUBLIC_API_URL=$NFT_COMMON_BASE_PUBLIC_API_URL
      - COMMON_OPENSEA_LAZY_MINT_ADDRESS=$NFT_COMMON_OPENSEA_LAZY_MINT_ADDRESS
      - COMMON_FACTORY_ERC-721-RARIBLE=$NFT_COMMON_FACTORY_ERC_721_RARIBLE
      - COMMON_FACTORY_ERC-721-RARIBLE-USER=$NFT_COMMON_FACTORY_ERC_721_RARIBLE_USER
      - COMMON_FACTORY_ERC-1155-RARIBLE=$NFT_COMMON_FACTORY_ERC_1155_RARIBLE
      - COMMON_FACTORY_ERC-1155-RARIBLE-USER=$NFT_COMMON_FACTORY_ERC_1155_RARIBLE_USER
      - COMMON_ROYALTY_REGISTRY_ADDRESS=$NFT_COMMON_ROYALTY_REGISTRY_ADDRESS
      - COMMON_KAFKA_REPLICA_SET=$KAFKA_CONNECTION_STRING
      - COMMON_BLOCKCHAIN=$NFT_COMMON_BLOCKCHAIN
      - BLOCKCHAIN_SCANNER_KAFKA_BROKER-REPLICA-SET=$KAFKA_CONNECTION_STRING

  protocol-zookeeper-1:
    image: zookeeper:3.7.0
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=protocol-zookeeper-1:2888:3888;2181
    volumes:
      - protocol-zookeeper-1:/data
      - protocol-zookeeper-log-1:/datalog

  protocol-kafka-1:
    image: confluentinc/cp-kafka:6.1.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://protocol-kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "protocol-zookeeper-1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_NUM_PARTITIONS: 9
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - protocol-kafka-1:/var/lib/kafka/data
    depends_on:
      - "protocol-zookeeper-1"

  protocol-mongodb:
    image: mongo:4.0.21
    command: --port 27017 --wiredTigerCacheSizeGB 1
    volumes:
      - protocol-mongodb:/data/db
    ports:
      - "47017:27017"

  protocol-ethereum:
    image: rarible/openethereum
    command: >
      --network-id 18
      --chain /home/openethereum/.local/share/config/openethereum/chain.json
      --base-path /home/openethereum/.local/share/openethereum/
      --jsonrpc-interface all
      --jsonrpc-cors all
      --unsafe-expose
    user: root:root
    volumes:
      - protocol-ethereum:/home/openethereum/.local/share/openethereum/
    ports:
      - "8545:8545"

  protocol-redis:
    image: redis:6.0.9
    volumes:
      - protocol-redis:/data

volumes:
  protocol-zookeeper-1: {}
  protocol-zookeeper-log-1: {}
  protocol-kafka-1: {}
  protocol-mongodb: {}
  protocol-ethereum: {}
  protocol-redis: {}
