application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: protocol-${common.blockchain}-order-listener
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive
mongock:
  change-logs-scan-package:
    - com.rarible.ethereum.listener.log.mongock

rarible:
  ethereum:
    converter:
      enabled: true
    read-only-transaction-sender:
      enabled: true
  core:
    contract:
      enabled: true

protocol:
  nft:
    subscriber:
      blockchain: ${common.blockchain}
  erc20:
    subscriber:
      blockchain: ${common.blockchain}

common:
  eip712-domain-name: Exchange
  eip712-domain-version: 2

listener:
  priceUpdateScheduleRate: PT12H # 12 hours to ms
  priceUpdateEnabled: false
  resetMakeStockScheduleRate: PT1H # 1 hour period
  resetMakeStockEnabled: false

ethereumMaxFrameSize: 209715200
ethereumBlockBatchSize: 50
