application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: protocol-${common.blockchain}-nft-order-listener
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive
mongock:
  change-logs-scan-package:
    - com.rarible.protocol.nftorder.core.migration

protocol:
  nft:
    subscriber:
      blockchain: ${common.blockchain}
  unlockable:
    subscriber:
      blockchain: ${common.blockchain}
  order:
    subscriber:
      blockchain: ${common.blockchain}

listener:
  orderConsumerCount: 5
  ownershipConsumerCount: 2
  job:
    reconciliation:
      order:
        batch-size: 50
  event-producer:
    environment: ${application.environment}
    kafka-replica-set: ${kafka.hosts}

