application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: protocol-${common.blockchain}-nft-migration
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  ethereum:
    converter:
      enabled: true
    read-only-transaction-sender:
      enabled: true

mongock:
  change-logs-scan-package:
    - com.rarible.protocol.nft.migration.mongock.mongo

common:
  cryptoPunksContractAddress: "0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB"

ipfs:
  upload_proxy: "https://pinata.rarible.com/upload"
  gateway: "https://rarible.mypinata.cloud/ipfs"
  cryptoPunksImagesUrl: "https://rarible.mypinata.cloud/ipfs/QmVRJcGax4AavhGCJp4oxGC7264qPNdWHwQCsdSN8bs2YD"
