application:
  environment: infura-test

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  cloud:
    bootstrap:
      enabled: false
    consul:
      enabled: false

rarible:
  ethereum:
    httpUrl: ${ETH_NODE_HTTP_URL}
    websocketUrl: ${ETH_NODE_WS_URL}
  core:
    apm:
      agent:
        enabled: false

common:
  feature-flags:
    scanner-version: V2
    reduce-version: V2
  kafka-replica-set: ${KAFKA_HOSTS}

blockchain:
  scanner:
    ethereum:
      scan:
        batch-load:
          batch-size: 50
    kafka:
      broker-replica-set: ${KAFKA_HOSTS}

