global:
  network: 'testnet'

sharedEnvironments: &sharedEnvironments
  SPRING_CLOUD_CONSUL_ENABLED: false
  APPLICATION_ENVIRONMENT: infura-test
  SPRING_CLOUD_BOOTSTRAP_ENABLED: false
  RARIBLE_CORE_APM_AGENT_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_DESTINATIONS: []
  RARIBLE_ETHEREUM_MAX-FRAME-SIZE: 10485760
  COMMON_KAFKAREPLICASET: '{{ .Values.environments.KAFKA_HOSTS }}'
  RARIBLE_LOADER_BROKERREPLICASET: '{{ .Values.environments.KAFKA_HOSTS }}'
  BLOCKCHAIN_SCANNER_KAFKA_BROKERREPLICASET: '{{ .Values.environments.KAFKA_HOSTS }}'
  # this secrets assigns automatically
  # RARIBLE_CORE_AGENT_SERVER:
  # KAFKA_HOSTS:
  # SPRING_DATA_MONGODB_PASSWORD:
  # SPRING_DATA_MONGODB_USER:
  # SPRING_DATA_MONGODB_URI:
  # ETH_NODE_HTTP_URL:
  # ETH_NODE_WS_URL:

ethereum-erc20-api:
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20

ethereum-erc20-listener:
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20
    SPRING_TASK_SCHEDULING_POOL_SIZE: 30
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    ETHEREUMMAXPROCESSTIME: 1200000
    USENEWMONGOINDEX: true

ethereum-gateway:
  environments:
    <<: *sharedEnvironments
    RARIBLE_CORE_NGINXEXPOSE_ENABLED: false

ethereum-order-api:
  environments:
    <<: *sharedEnvironments

ethereum-order-listener:
  environments:
    <<: *sharedEnvironments

ethereum-order-migration:
  environments:
    <<: *sharedEnvironments

ethereum-unlockable-api:
  environments:
    <<: *sharedEnvironments

ethereum-nft-api: 
  environments:
    <<: *sharedEnvironments
    RARIBLE_LOADER_LOADTASKSBATCHSIZE: 50
    RARIBLE_LOADER_WORKERS: 32
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    ETHEREUMMAXPROCESSTIME: 1200000
    USENEWMONGOINDEX: true
    API_CHAINID: 420

ethereum-nft-listener:
  environments:
    <<: *sharedEnvironments
    COMMON_FEATUREFLAGS_SCANNERVERSION: V2
    COMMON_FEATUREFLAGS_REDUCEVERSION: V2
    BLOCKCHAIN_SCANNER_ETHEREUM_SCAN_BATCHLOAD_BATCHSIZE: 50

ethereum-nft-migration:
  environments:
    <<: *sharedEnvironments
