global:
  network: 'testnet'

sharedEnvironments: &sharedEnvironments
  SPRING_CLOUD_CONSUL_ENABLED: false
  SPRING_CLOUD_BOOTSTRAP_ENABLED: false
  SPRING_PROFILES_ACTIVE: '{{ .Values.global.blockchain }},{{ include "service.appEnv" $ }},{{ .Values.global.blockchain }}-{{ include "service.appEnv" $ }}'
  RARIBLE_CORE_APM_AGENT_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_DESTINATIONS: ""
  RARIBLE_ETHEREUM_MAXFRAMESIZE: 10485760
  COMMON_CRYPTOPUNKSCONTRACTADDRESS: '0x85252f525456d3fce3654e56f6eaf034075e231c'
  COMMON_OPENSEALAZYMINTADDRESS: '0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656'
  COMMON_ROYALTYREGISTRYADDRESS: '0xdA8e7D4cF7BA4D5912a68c1e40d3D89828fA6EE8'
  COMMON_FACTORY_ERC721RARIBLE: "0x31575E4426d195f6082aDdcD44e97cB4CEa1291C"
  COMMON_FACTORY_ERC721RARIBLEUSER: "0xe5bF86F2FC1e0C704A8b2C095aD92C59100C63Ac"
  COMMON_FACTORY_ERC1155RARIBLE: "0x3Df4035EC62B97b5e3B5f160Cb84dCe4A9CB545D"
  COMMON_FACTORY_ERC1155RARIBLEUSER: "0x5a5773ac6b87f15dF215A78BEfdce478C33D8418"
  # this secrets assigns automatically
  # RARIBLE_CORE_AGENT_SERVER:
  # SPRING_DATA_MONGODB_HOST:
  # SPRING_DATA_MONGODB_PORT:
  # SPRING_DATA_MONGODB_USERNAME:
  # SPRING_DATA_MONGODB_PASSWORD:
  # COMMON_KAFKAREPLICASET:
  # COMMON_BASEPUBLICAPIURL: 
  # BLOCKCHAIN_SCANNER_KAFKA_BROKERREPLICASET:
  # RARIBLE_LOADER_BROKERREPLICASET: 
  # RARIBLE_ETHEREUM_HTTPURL: 
  # RARIBLE_ETHEREUM_WEBSOCKETURL:

ethereum-erc20-api:
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20

ethereum-erc20-listener:
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20
    SPRING_TASK_SCHEDULING_POOL_SIZE: 30
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    ETHEREUMMAXPROCESSTIME: 1200000
    USENEWMONGOINDEX: true

ethereum-gateway:
  environments:
    <<: *sharedEnvironments
    RARIBLE_CORE_NGINXEXPOSE_ENABLED: false

ethereum-order-api:
  environments:
    <<: *sharedEnvironments

ethereum-order-listener:
  environments:
    <<: *sharedEnvironments

ethereum-order-migration:
  environments:
    <<: *sharedEnvironments

ethereum-unlockable-api:
  environments:
    <<: *sharedEnvironments

ethereum-nft-api: 
  environments:
    <<: *sharedEnvironments
    RARIBLE_LOADER_LOADTASKSBATCHSIZE: 50
    RARIBLE_LOADER_WORKERS: 32
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    ETHEREUMMAXPROCESSTIME: 1200000
    USENEWMONGOINDEX: true
    API_CHAINID: 420
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft

ethereum-nft-listener:
  environments:
    <<: *sharedEnvironments
    COMMON_FEATUREFLAGS_SCANNERVERSION: V2
    COMMON_FEATUREFLAGS_REDUCEVERSION: V2
    BLOCKCHAIN_SCANNER_ETHEREUM_SCAN_BATCHLOAD_BATCHSIZE: 50
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft

ethereum-nft-migration:
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft
