global:
  network: 'testnet'

sharedEnvironments: &sharedEnvironments
  SPRING_CLOUD_CONSUL_ENABLED: false
  SPRING_CLOUD_BOOTSTRAP_ENABLED: false
  SPRING_PROFILES_ACTIVE: '{{ .Values.global.blockchain }},{{ include "service.appEnv" $ }},{{ .Values.global.blockchain }}-{{ include "service.appEnv" $ }}'
  RARIBLE_CORE_APM_AGENT_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_DESTINATIONS: ""
  RARIBLE_ETHEREUM_MAXFRAMESIZE: 10485760
  COMMON_CRYPTOPUNKSCONTRACTADDRESS: '0x85252f525456d3fce3654e56f6eaf034075e231c'
  COMMON_OPENSEALAZYMINTADDRESS: '0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656'
  COMMON_ROYALTYREGISTRYADDRESS: '0xdA8e7D4cF7BA4D5912a68c1e40d3D89828fA6EE8'
  COMMON_FACTORY_ERC721RARIBLE: "0x31575E4426d195f6082aDdcD44e97cB4CEa1291C"
  COMMON_FACTORY_ERC721RARIBLEUSER: "0xe5bF86F2FC1e0C704A8b2C095aD92C59100C63Ac"
  COMMON_FACTORY_ERC1155RARIBLE: "0x3Df4035EC62B97b5e3B5f160Cb84dCe4A9CB545D"
  COMMON_FACTORY_ERC1155RARIBLEUSER: "0x5a5773ac6b87f15dF215A78BEfdce478C33D8418"
  API_CHAINID: 5
  COMMON_CHAINID: 5
  # this secrets assigns automatically
  # RARIBLE_CORE_AGENT_SERVER:
  # SPRING_DATA_MONGODB_HOST:
  # SPRING_DATA_MONGODB_PORT:
  # SPRING_DATA_MONGODB_USERNAME:
  # SPRING_DATA_MONGODB_PASSWORD:
  # COMMON_KAFKAREPLICASET:
  # COMMON_BASEPUBLICAPIURL: 
  # BLOCKCHAIN_SCANNER_KAFKA_BROKERREPLICASET:
  # RARIBLE_LOADER_BROKERREPLICASET: 
  # RARIBLE_ETHEREUM_HTTPURL: 
  # RARIBLE_ETHEREUM_WEBSOCKETURL:

sharedTolerations: &sharedTolerations
  effect: NoSchedule
  key: env
  operator: Equal
  value: infura-test

ethereum-erc20-api:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20

ethereum-erc20-listener:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20
    SPRING_TASK_SCHEDULING_POOL_SIZE: 30
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    ETHEREUMMAXPROCESSTIME: 1200000
    USENEWMONGOINDEX: true

ethereum-gateway:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    RARIBLE_CORE_NGINXEXPOSE_ENABLED: false

orderEnvironment: &orderEnvironment
    COMMON_AUCTIONCONTRACTADDRESSES_V1: "0xA8B4ab8aE8C40cD6b11a3A6BFCb00B2B8106150f"
    COMMON_EXCHANGECONTRACTADDRESSES_CRYPTOPUNKS: "0xaf2584a8b198f5d0b360b95d92aec852f7902e52"
    COMMON_EXCHANGECONTRACTADDRESSES_HOLDERV1: "0x0000000000000000000000000000000000000000"
    COMMON_EXCHANGECONTRACTADDRESSES_OPENSEAV1: "0x5206e78b21ce315ce284fb24cf05e0585a93b1d9"
    COMMON_EXCHANGECONTRACTADDRESSES_OPENSEAV2: "0xdd54d660178b28f6033a953b0e55073cfa7e3744"
    COMMON_EXCHANGECONTRACTADDRESSES_V1: "0xda381535565b97640a6453fa7a1a7b161af78cbe"
    COMMON_EXCHANGECONTRACTADDRESSES_V2: "0xd4a57a3bD3657D0d46B4C5bAC12b3F156B9B886b"
    COMMON_EXCHANGECONTRACTADDRESSES_ZEROEX: "0x0000000000000000000000000000000000000000"
    COMMON_FEATUREFLAGS_SHOWALLORDERSBYDEFAULT: true
    COMMON_FEATUREFLAGS_SHOWOPENSEAORDERSWITHOTHERPLATFORMS: true
    COMMON_FEATUREFLAGS_USECOMMONTRANSACTIONTRACEPROVIDER: false
    COMMON_PUBLISH_PUBLISHOPENSEAORDERSTOCOMMONTOPIC: true
    COMMON_TRANSFERPROXYADDRESSES_CRYPTOPUNKSTRANSFERPROXY: "0xfc2aa1b3365b8e0cac7a7d22fd7655e643792d17"
    COMMON_TRANSFERPROXYADDRESSES_ERC1155LAZYTRANSFERPROXY: "0x0cF0AAb68432a3710ECbf2f1b112a11cEe31a83C"
    COMMON_TRANSFERPROXYADDRESSES_ERC20TRANSFERPROXY: "0x2fce8435f0455edc702199741411dbcd1b7606ca"
    COMMON_TRANSFERPROXYADDRESSES_ERC721LAZYTRANSFERPROXY: "0x0cF0AAb68432a3710ECbf2f1b112a11cEe31a83C"
    COMMON_TRANSFERPROXYADDRESSES_TRANSFERPROXY: "0x7d47126a2600e22eab9ed6cf0e515678727779a6"
    COMMON_PROTOCOLCOMMISSION: 0
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-order

ethereum-order-api:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    <<: *orderEnvironment

ethereum-order-listener:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    <<: *orderEnvironment
    BLOCKCHAIN_SCANNER_ETHEREUM_SCAN_BATCHLOAD_BATCHSIZE: 100
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    LISTENER_LOADOLDOPENSEAORDERS: true
    LISTENER_LOADOPENSEADELAY: "180s"
    LISTENER_LOADOPENSEAORDERVERSION: true
    LISTENER_LOADOPENSEAORDERS: true
    LISTENER_OPENSEANONCEINCREMENT: 1
    LISTENER_OPENSEAORDERSIDE: "SELL"
    LISTENER_PRICEUPDATEENABLED: true
    LISTENER_PUBLISHTASKDELAYMS: 100
    LISTENER_RESETMAKESTOCKENABLED: true
    LISTENER_UPDATESTATUSBYSTARTENDENABLED: true
    LISTENER_UPDATESTATUSBYSTARTENDRATE: "PT1M"
    RARIBLE_ETHEREUM_MAXFRAMESIZE: 209715200
    SPRING_TASK_SCHEDULING_POOL_SIZE: 60
    USENEWMONGOINDEX: true
ethereum-order-migration:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    <<: *orderEnvironment

ethereum-unlockable-api:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-unlockable
ethereum-nft-api: 
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    RARIBLE_LOADER_LOADTASKSBATCHSIZE: 50
    RARIBLE_LOADER_WORKERS: 32
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    ETHEREUMMAXPROCESSTIME: 1200000
    USENEWMONGOINDEX: true
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft

ethereum-nft-listener:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    COMMON_FEATUREFLAGS_SCANNERVERSION: V2
    COMMON_FEATUREFLAGS_REDUCEVERSION: V2
    BLOCKCHAIN_SCANNER_ETHEREUM_SCAN_BATCHLOAD_BATCHSIZE: 50
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft

ethereum-nft-migration:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft
