global:
  network: 'testnet'

sharedEnvironments: &sharedEnvironments
  SPRING_CLOUD_CONSUL_ENABLED: false
  APPLICATION_ENVIRONMENT: infura-test
  SPRING_CLOUD_BOOTSTRAP_ENABLED: false
  RARIBLE_CORE_APM_AGENT_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_DESTINATIONS: []
  # this secrets assigns automatically
  # RARIBLE_CORE_AGENT_SERVER:
  # KAFKA_HOSTS:
  # SPRING_DATA_MONGODB_PASSWORD:
  # SPRING_DATA_MONGODB_USER:
  # SPRING_DATA_MONGODB_URI:
  # ETH_NODE_HTTP_URL:
  # ETH_NODE_WS_URL:

ethereum-erc20-api:
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20
    RARIBLE_ETHEREUM_MAX-FRAME-SIZE: 10485760

ethereum-erc20-listener:
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20
    RARIBLE_ETHEREUM_MAX-FRAME-SIZE: 10485760
    SPRING_TASK_SCHEDULING_POOL_SIZE: 30
    ETHEREUM-BLOCK-PROCESSING-DELAY: 5000
    ETHEREUM-MAX-PROCESS-TIME: 1200000
    USE-NEW-MONGO-INDEX: true
    COMMON_KAFKA-REPLICA-SET: {{ .Values.environments.KAFKA_HOSTS }}

ethereum-gateway:
  environments:
    <<: *sharedEnvironments

ethereum-order-api:
  environments:
    <<: *sharedEnvironments

ethereum-order-listener:
  environments:
    <<: *sharedEnvironments

ethereum-order-migration:
  environments:
    <<: *sharedEnvironments

ethereum-unlockable-api:
  environments:
    <<: *sharedEnvironments

ethereum-nft-api: 
  environments:
    <<: *sharedEnvironments

ethereum-nft-listener:
  environments:
    <<: *sharedEnvironments

ethereum-nft-migration:
  environments:
    <<: *sharedEnvironments
