rarible:
  core:
    apm:
      agent:
        enabled: false
  ethereum:
    httpUrl: ${ETH_NODE_HTTP_URL}
    maxFrameSize: 10485760
    websocketUrl: ${ETH_NODE_WS_URL}
spring:
  cloud:
    bootstrap:
      enabled: false
    consul:
      enabled: false
  task:
    scheduling:
      pool:
        size: 30
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

ethereumBlockProcessingDelay: 5000
ethereumMaxProcessTime: 1200000
useNewMongoIndex: true

application:
  environment: infura-test

logging:
  logstash:
    tcp-socket:
      enabled: false
      destinations: []

common:
  kafka-replica-set: ${KAFKA_HOSTS}
